[package]
name = "dircopy"
version = "0.1.0"
authors = ["c86j2"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.6"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"