source_path = "C:\\Users\\c86j2\\Documents\\github\\c86j224s\\snippet\\Rust_Dir\\dircopy\\.example\\source"
target_path = "C:\\Users\\c86j2\\Documents\\github\\c86j224s\\snippet\\Rust_Dir\\dircopy\\.example\\target"